services:
  express-gateway:
    container_name: express-api-gateway
    build:
      context: .
    ports:
      - "${PORT}:8002"
    volumes:
      - .:/usr/src/app
    environment:
      - NODE_ENV=${ENV}
  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "${NFINX_PORT}:80"
    depends_on:
      - express-gateway
    volumes:
      - ${CONF_PATH}/nginx.conf:/etc/nginx/nginx.conf
  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - ${DATA_PATH}/redis:/data
  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    ports:
      - "${GRAFANA_PORT}:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
    volumes:
      - ${DATA_PATH}/grafana:/var/lib/grafana
  loki:
    container_name: loki
    image: grafana/loki:latest
    user: "root"
    ports:
      - "${LOKI_PORT}:3100"
    volumes:
      - ${CONF_PATH}/loki.yaml:/etc/loki/local-config.yaml
      - ${DATA_PATH}/loki:/loki
    command: -config.file=/etc/loki/local-config.yaml
  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    ports:
      - "${PROMETHEUS_PORT}:9090"
    volumes:
      - ${CONF_PATH}/prometheus.yml:/etc/prometheus/prometheus.yml
      - ${DATA_PATH}/prometheus:/prometheus
  influxdb:
    image: influxdb:1.8
    container_name: influxdb_v1
    ports:
      - "${INFLUXDB_PORT}:8086"
    environment:
      INFLUXDB_DB: ${INFLUXDB_NAME}
      INFLUXDB_ADMIN_USER: ${INFLUXDB_USER}
      INFLUXDB_ADMIN_PASSWORD: ${INFLUXDB_PASSWORD}
    volumes:
      - ${DATA_PATH}/influxdb:/var/lib/influxdb
