global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: "express-api-gateway"
    static_configs:
      - targets: ["express-api-gateway:8002"]
  - job_name: "loki"
    static_configs:
      - targets: ["loki:3100"]
