{
 "title": "Loggers",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "api-gateway",
   "type": "logs",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{job=\"api-gateway\"}\n"
    }
   ]
  },
  {
   "title": "Nginx Info Logs",
   "type": "logs",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "{job=\"nginx\"} | json | level=\"info\""
    }
   ]
  },
  {
   "title": "Nginx Error Logs",
   "type": "logs",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "{job=\"nginx\"} | json | level=\"error\""
    }
   ]
  }
 ]
}